name: matrix
on: push

jobs:
  Node-versions:
    strategy:
      matrix:
        node-version: [16,20]
        os: [ macos-latest,windows-latest,ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: after setup node version
        run: node -v