name: Build and test node in docker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up docker-buildx
        uses: docker/setup-buildx-action@v3
      - name: build docker image
        run: docker build -t ubuntu-node .
      - name: run docker container
        run: docker run -d --name imgcn ubuntu-node
      - name: execute shell
        run: docker exec imgcn bash -c "node --version"
      - name: stop container
        run: docker stop imgcn
  