name: matrix
on: push

jobs:
  Node-versions:
    strategy:
      matrix:
        node-version: [6,7,8]
    runs-on: ubuntu-latest
    steps:
      - name: node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: after setup node version
        run: node -v